version: "3"

services:
  mc-new:
    image: itzg/minecraft-server:java17-jdk
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      MOTD: "New Minecraft Server wiz Old Data. Hell Yeah"
      DIFFICULTY: hard
      MEMORY: 1G
      OVERRIDE_SERVER_PROPERTIES: "true"
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      - /docker-data/mc/data:/data
  mc-2023:
    image: itzg/minecraft-server:latest
    ports:
      - 25566:25565
    environment:
      EULA: "TRUE"
      MOTD: "2023 New Minecraft Server. Hell Yeah"
      DIFFICULTY: hard
      MEMORY: 1G
      OVERRIDE_SERVER_PROPERTIES: "true"
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      - /docker-data/mc-2023/data:/data